[package]
name = "minimal_update_service_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncomm = { path = "../ncomm" }
ncomm_macro_derive = { path = "../ncomm/ncomm_macro_derive" }