[package]
name = "minimal_update_service_client"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncomm = { path = "../../", version = "0.1.2" }